<a href="https://colab.research.google.com/github/gorzanskik-ai/machine-learning/blob/main/supervised-learning/02_regression/01_linear_regression_normal_equation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
X1 = np.array([1, 2, 3, 4, 5, 6])
Y = np.array([3000, 3250, 3500, 3750, 4000, 4250])
m = len(X1)

print(f'Lata pracy: {X1}')
print(f'Wynagrodzenie: {Y}')
print(f'Liczba próbek: {m}')

Lata pracy: [1 2 3 4 5 6]
Wynagrodzenie: [3000 3250 3500 3750 4000 4250]
Liczba próbek: 6


In [3]:
X1 = X1.reshape(m, 1)
X1

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [5]:
bias = np.ones((m, 1))
bias

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [9]:
X = np.c_[bias, X1] #lub np za pomoca append: np.append(bias, X1, axis=1)
X

array([[1., 1.],
       [1., 2.],
       [1., 3.],
       [1., 4.],
       [1., 5.],
       [1., 6.]])

In [10]:
Y = Y.reshape(m, 1)
Y

array([[3000],
       [3250],
       [3500],
       [3750],
       [4000],
       [4250]])

Obliczenie równania normalnego

In [11]:
np.dot(X.T, X)

array([[ 6., 21.],
       [21., 91.]])

In [12]:
L = np.linalg.inv(np.dot(X.T, X))
P = np.dot(X.T, Y)
W = np.dot(L, P)
W

array([[2750.],
       [ 250.]])

#Z pomocą scikit-learn

In [15]:
from sklearn.linear_model import LinearRegression

LR = LinearRegression()
LR.fit(X1, Y)

print(LR.intercept_)    #współczynnik w0
print(LR.coef_) #współczynnik w1 

[2750.]
[[250.]]
