<a href="https://colab.research.google.com/github/gorzanskik-ai/machine-learning/blob/main/supervised-learning/03_classification/07_naive_bayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np
import pandas as pd
import sklearn

np.random.seed(42)
np.set_printoptions(precision=6, suppress=True)
sklearn.__version__

'1.0.2'

In [8]:
pogoda = ['słonecznie', 'deszczowo', 'pochmurno', 'deszczowo', 'słonecznie', 'słonecznie',
          'pochmurno', 'pochmurno', 'słonecznie']
temperatura = ['ciepło', 'zimno', 'ciepło', 'ciepło', 'ciepło', 'umiarkowanie',
               'umiarkowanie', 'ciepło', 'zimno']

spacer = ['tak', 'nie', 'tak', 'nie', 'tak', 'tak', 'nie', 'tak', 'nie']      

raw_df = pd.DataFrame(data={'pogoda': pogoda, 'temperatura': temperatura, 'spacer': spacer})
df = raw_df.copy()
df

pogoda   temperatura spacer
0  słonecznie        ciepło    tak
1   deszczowo         zimno    nie
2   pochmurno        ciepło    tak
3   deszczowo        ciepło    nie
4  słonecznie        ciepło    tak
5  słonecznie  umiarkowanie    tak
6   pochmurno  umiarkowanie    nie
7   pochmurno        ciepło    tak
8  słonecznie         zimno    nie

In [9]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
df['spacer']= encoder.fit_transform(spacer)

In [11]:
df = pd.get_dummies(df, columns=['pogoda', 'temperatura'], drop_first=True)
df.head()

spacer  pogoda_pochmurno  pogoda_słonecznie  temperatura_umiarkowanie  \
0       1                 0                  1                         0   
1       0                 0                  0                         0   
2       1                 1                  0                         0   
3       0                 0                  0                         0   
4       1                 0                  1                         0   

   temperatura_zimno  
0                  0  
1                  1  
2                  0  
3                  0  
4                  0

In [13]:
X = df.drop('spacer', axis=1).copy()
y = df['spacer']

In [16]:
X = X.values
y = y.values

Model

In [17]:
from sklearn.naive_bayes import GaussianNB

classifier = GaussianNB()
classifier.fit(X, y)

GaussianNB()

In [18]:
classifier.score(X, y)

0.7777777777777778

In [28]:
classifier.predict(X)

array([1, 0, 1, 1, 1, 1, 1, 1, 0])

In [29]:
classifier.predict_proba(X)

array([[0.000006, 0.999994],
       [1.      , 0.      ],
       [0.000015, 0.999985],
       [0.000037, 0.999963],
       [0.000006, 0.999994],
       [0.000011, 0.999989],
       [0.000025, 0.999975],
       [0.000015, 0.999985],
       [1.      , 0.      ]])

In [30]:
encoder.classes_

array(['nie', 'tak'], dtype='<U3')

In [32]:
classifier.predict(X[0].reshape(1, -1))

array([1])

In [33]:
X[0].reshape(1, -1)

array([[0, 1, 0, 0]], dtype=uint8)

In [34]:
np.array([1, 2, 3])

array([1, 2, 3])

In [35]:
np.array([1, 2, 3]).reshape(-1, 1)

array([[1],
       [2],
       [3]])

In [36]:
np.array([1, 2, 3]).reshape(1, -1)

array([[1, 2, 3]])